#!/bin/sh
echo "what is the name of the movie:"
read dirname
cd /tmp
ls -l|grep Fla|awk -F" " '{ print $7" "$8}' |sort|awk -F" " '{ print  $2 }'>youku.tmp
for n in $(seq 1 1 100)
do
    read file<youku.tmp
    if [ -z $file ]
    then
        echo "no file..now"
        break
    fi
    sed '1d' youku.tmp >youku2.tmp #remove the first line of the file
    mv youku2.tmp youku.tmp
    echo $n
    echo $file
    cp $file "movie-"$n".flv"
done
rm youku.tmp
mkdir $HOME/Desktop/$dirname
echo "copying file, plz wait..."
mv movie* $HOME/Desktop/$dirname
echo "done"

